version: '3'

services:
    pyquil:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8888:8888"
        volumes:
            - .:/home
        command: jupyter notebook --ip='*' --port=8888 --no-browser --allow-root --notebook-dir=/home